# Generated by Django 4.2 on 2023-04-20 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novatarefa',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='novatarefa',
            name='data_inicio_planejado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
