# Generated by Django 4.2 on 2023-04-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_remove_novatarefa_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novatarefa',
            name='status_tarefa',
            field=models.CharField(choices=[('N', 'Não Iniciado'), ('E', 'Em andamento'), ('C', 'Concluido')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
