# Generated by Django 3.2.18 on 2023-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_novatarefa_status_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_realizado',
            field=models.DateTimeField(blank=True),
        ),
    ]
