# Generated by Django 3.2.18 on 2023-05-03 12:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_auto_20230503_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 12, 36, 19, 583900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_inicio_planejado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
