# Generated by Django 3.2.18 on 2023-05-03 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_remove_usuariosprojeto_fav_user_content_and_more'),
        ('tarefas', '0006_auto_20230503_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 12, 37, 47, 903898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='membros',
            field=models.ManyToManyField(to='projetos.UsuariosProjeto'),
        ),
    ]
