# Generated by Django 3.2.18 on 2023-05-03 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_novatarefa_data_fim_planejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 12, 47, 0, 119683, tzinfo=utc)),
        ),
    ]
