# Generated by Django 3.2.18 on 2023-05-03 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_remove_usuariosprojeto_fav_user_content_and_more'),
        ('tarefas', '0012_auto_20230503_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 13, 12, 55, 20, 784892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.novoprojeto'),
        ),
    ]
