# Generated by Django 3.2.18 on 2023-05-05 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0016_auto_20230503_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novatarefa',
            name='membros',
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 16, 46, 5, 502346, tzinfo=utc)),
        ),
    ]
