# Generated by Django 3.2.18 on 2023-05-05 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0017_auto_20230505_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 16, 47, 12, 553539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_realizado',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 5, 16, 47, 12, 553539, tzinfo=utc)),
        ),
    ]
