# Generated by Django 3.2.18 on 2023-05-05 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0020_auto_20230505_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 17, 40, 9, 362245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_realizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
