# Generated by Django 4.2 on 2023-05-20 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0031_alter_novatarefa_data_fim_planejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 18, 56, 26, 526747, tzinfo=datetime.timezone.utc)),
        ),
    ]
