# Generated by Django 4.2 on 2023-06-10 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0032_alter_novatarefa_data_fim_planejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 22, 57, 41, 406804, tzinfo=datetime.timezone.utc)),
        ),
    ]
