# Generated by Django 4.2 on 2023-06-14 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0034_alter_novatarefa_data_fim_planejado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novatarefa',
            name='data_fim_planejado',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 0, 0, 38, 389303, tzinfo=datetime.timezone.utc)),
        ),
    ]
