# Generated by Django 4.1.5 on 2023-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0002_rename_demanda_novademanda"),
    ]

    operations = [
        migrations.DeleteModel(name="NovaDemanda",),
    ]
