# Generated by Django 3.2.18 on 2023-04-17 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0002_auto_20230416_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoprojeto',
            name='equipe',
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
