# Generated by Django 3.2.18 on 2023-04-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandas', '0001_initial'),
        ('projetos', '0003_delete_novademanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NovoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('staramais', models.BooleanField(default=False)),
                ('staralabs', models.BooleanField(default=False)),
                ('prioridade', models.PositiveIntegerField(default=1)),
                ('equipe', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projetos.faseprojeto')),
                ('nome_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.novademanda')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projetos.statusprojeto')),
            ],
        ),
    ]
