# Generated by Django 3.2.18 on 2023-04-17 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0003_auto_20230417_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoprojeto',
            name='equipe',
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='equipe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
