# Generated by Django 3.2.18 on 2023-04-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20230417_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novoprojeto',
            name='fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.faseprojeto'),
        ),
        migrations.AlterField(
            model_name='novoprojeto',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.statusprojeto'),
        ),
    ]
