# Generated by Django 4.2 on 2023-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_novoprojeto_nome_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='novoprojeto',
            name='descricao_projeto',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
