# Generated by Django 4.2 on 2023-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_alter_novoprojeto_descricao_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novoprojeto',
            name='prioridade',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
