# Generated by Django 3.2.18 on 2023-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_alter_novoprojeto_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='novoprojeto',
            name='categoria',
            field=models.CharField(choices=[('M', 'Melhoria'), ('P', 'Projeto')], default='M', max_length=50),
        ),
    ]
