# Generated by Django 3.2.18 on 2023-04-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_auto_20230425_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoprojeto',
            name='equipe',
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='membros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.usuariosprojeto'),
        ),
    ]
