# Generated by Django 3.2.18 on 2023-04-25 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0011_auto_20230425_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novoprojeto',
            name='equipe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
