# Generated by Django 3.2.18 on 2023-04-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0014_auto_20230425_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosprojeto',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuariosprojeto',
            name='recebe_email',
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='membros',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.perfilusuarios'),
        ),
        migrations.AddField(
            model_name='novoprojeto',
            name='recebe_email',
            field=models.BooleanField(default=False),
        ),
    ]
