# Generated by Django 3.2.18 on 2023-04-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_auto_20230425_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuariosProjeto',
        ),
    ]
