# Generated by Django 3.2.18 on 2023-04-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0016_delete_usuariosprojeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novoprojeto',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='novoprojeto',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='novoprojeto',
            name='recebe_email',
        ),
        migrations.CreateModel(
            name='UsuariosProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebe_email', models.BooleanField(default=False)),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.perfilusuarios')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.novoprojeto')),
            ],
        ),
    ]
