# Generated by Django 3.2.18 on 2023-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_auto_20230425_1404'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuariosprojeto',
            constraint=models.UniqueConstraint(fields=('nome', 'projeto'), name='fav_user_content'),
        ),
    ]
