# Generated by Django 4.2 on 2023-04-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_usuariosprojeto_fav_user_content'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuariosprojeto',
            name='fav_user_content',
        ),
        migrations.RenameField(
            model_name='usuariosprojeto',
            old_name='nome',
            new_name='usuario',
        ),
        migrations.AddConstraint(
            model_name='usuariosprojeto',
            constraint=models.UniqueConstraint(fields=('usuario', 'projeto'), name='fav_user_content'),
        ),
    ]
