# Generated by Django 4.2 on 2023-05-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_remove_usuariosprojeto_fav_user_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novoprojeto',
            options={'verbose_name': 'Projeto'},
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('corpo', models.TextField()),
                ('enviado', models.BooleanField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.novoprojeto')),
            ],
        ),
    ]
