# Generated by Django 4.2 on 2023-05-07 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_rename_vaga_emails_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Emails Enviado'},
        ),
        migrations.AddField(
            model_name='emails',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
