# Generated by Django 4.2 on 2023-05-14 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0022_alter_emails_options_emails_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('I', 'Informação'), ('P', 'Pendência'), ('O', 'Outros')], default='M', max_length=50)),
                ('local', models.CharField(max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.novoprojeto')),
                ('usuario_assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.usuariosprojeto')),
            ],
        ),
    ]
