# Generated by Django 4.2 on 2023-05-16 00:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0023_ata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ata',
            old_name='descricao',
            new_name='atividadeouassunto',
        ),
        migrations.RenameField(
            model_name='ata',
            old_name='usuario_assunto',
            new_name='participantes',
        ),
        migrations.AddField(
            model_name='ata',
            name='data_hora_reunião',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ata',
            name='distribuido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distribuido', to='projetos.usuariosprojeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ata',
            name='quando',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ata',
            name='quem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quem', to='projetos.usuariosprojeto'),
            preserve_default=False,
        ),
    ]
