# Generated by Django 3.2.18 on 2023-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novademanda',
            name='setor',
        ),
        migrations.AlterField(
            model_name='novademanda',
            name='categoria',
            field=models.CharField(choices=[('M', 'Melhoria'), ('P', 'Projeto')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novademanda',
            name='status',
            field=models.CharField(choices=[('P', 'Aguardando Priorizacao'), ('A', 'Em analise')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.DeleteModel(
            name='StatusBacklog',
        ),
    ]
