# Generated by Django 3.2.18 on 2023-04-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novademanda',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='novademanda',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='novademanda',
            name='status',
        ),
        migrations.RemoveField(
            model_name='novademanda',
            name='usuario_criacao',
        ),
    ]
