# Generated by Django 3.2.18 on 2023-04-06 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandas', '0002_auto_20230406_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='novademanda',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='demandas.categoria'),
        ),
        migrations.AddField(
            model_name='novademanda',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='demandas.setor'),
        ),
        migrations.AddField(
            model_name='novademanda',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='demandas.statusbacklog'),
        ),
        migrations.AddField(
            model_name='novademanda',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
