# Generated by Django 3.2.18 on 2023-04-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_auto_20230409_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novademanda',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='demandas.setor'),
        ),
    ]
