# Generated by Django 3.2.18 on 2023-04-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_rename_setor_novademanda_setor_demanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novademanda',
            name='setor_demanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='demandas.setor'),
        ),
    ]
