# Generated by Django 3.2.18 on 2023-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_alter_novademanda_setor_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novademanda',
            name='setor_demanda',
        ),
        migrations.AddField(
            model_name='novademanda',
            name='setor_demanda',
            field=models.ManyToManyField(to='demandas.Setor'),
        ),
    ]
