# Generated by Django 3.2.18 on 2023-04-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0008_auto_20230409_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novademanda',
            name='setor_demanda',
        ),
        migrations.AddField(
            model_name='novademanda',
            name='setor_demanda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='demandas.setor'),
            preserve_default=False,
        ),
    ]
