# Generated by Django 3.2.18 on 2023-04-09 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandas', '0009_auto_20230409_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novademanda',
            name='usuario_criacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
