# Generated by Django 4.2 on 2023-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0011_auto_20230416_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novademanda',
            name='base_calculo_retorno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='novademanda',
            name='nome_solicitante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='novademanda',
            name='retorno_qualitativo',
            field=models.TextField(),
        ),
    ]
