# Generated by Django 3.2.18 on 2023-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0012_alter_novademanda_base_calculo_retorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novademanda',
            name='categoria',
        ),
    ]
