# Generated by Django 3.2.18 on 2023-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0013_remove_novademanda_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novademanda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
