# Generated by Django 4.2 on 2023-05-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0014_alter_novademanda_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novademanda',
            options={'verbose_name': 'Demanda'},
        ),
    ]
