# Generated by Django 4.2 on 2023-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0015_alter_novademanda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
