# Generated by Django 4.2 on 2023-05-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0016_statusbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='novademanda',
            name='novo_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demandas.statusbacklog'),
            preserve_default=False,
        ),
    ]
