# Generated by Django 4.2 on 2023-05-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0017_novademanda_novo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novademanda',
            old_name='novo_status',
            new_name='status_backlog',
        ),
        migrations.RemoveField(
            model_name='novademanda',
            name='status',
        ),
    ]
