# Generated by Django 4.2 on 2023-06-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0018_rename_novo_status_novademanda_status_backlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadeUserStorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_demanda_requisito', models.PositiveIntegerField(default=999999)),
                ('descricao_requisito', models.TextField()),
                ('aprovacao', models.BooleanField(default=False)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.novademanda')),
            ],
        ),
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storie', models.PositiveIntegerField(default=999999)),
                ('historia', models.TextField()),
                ('aceitacao', models.TextField()),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.prioridadeuserstorie')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.requisitos')),
            ],
        ),
    ]
