# Generated by Django 4.2 on 2023-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0019_prioridadeuserstorie_requisitos_userstories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitos',
            options={'verbose_name': 'Requisito'},
        ),
        migrations.AlterModelOptions(
            name='userstories',
            options={'verbose_name': 'UserStorie'},
        ),
        migrations.RemoveField(
            model_name='requisitos',
            name='id_demanda_requisito',
        ),
        migrations.AddField(
            model_name='requisitos',
            name='nome',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
