# Generated by Django 4.2 on 2023-06-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandas', '0020_alter_requisitos_options_alter_userstories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitos',
            name='usuario_criacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
